NOISSUE - Create repo structure and workflows
mainflux/migrations pull request #1
Opened 2023-03-09 18:43 UTC by SammyOina

### What does this do?
Initialize repo strucutre and add workflows

### Which issue(s) does this PR fix/relate to?
None

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### Notes

2023-03-10 14:50 UTC, dborovcanin requested changes
DCO is failing. At least we know checks work. :)

2023-03-10 16:13 UTC, SammyOina commented
> DCO is failing. At least we know checks work. :)

all commits now signed, DCO is passing

2023-03-16 08:20 UTC, dborovcanin requested changes

2023-03-16 08:20 UTC, dborovcanin commented on .github/workflows/ci.yml
> +        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.out ./...
Add an empty line.

2023-03-16 08:20 UTC, dborovcanin commented on .gitignore
> +go.work
Same.

2023-04-19 10:42 UTC, dborovcanin requested changes

2023-04-19 10:42 UTC, dborovcanin commented on .github/workflows/ci.yml
> +        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.out ./...
@SammyOina Please do not mark it as resolved but rather actually resolve comments.

2023-04-19 10:42 UTC, dborovcanin commented on .gitignore
> +go.work
Same.

2023-04-19 10:42 UTC, dborovcanin commented on README.md
> +# migrations
Start Titles with capital letters.

2023-04-20 15:41 UTC, rodneyosodo requested changes

2023-04-20 15:41 UTC, rodneyosodo commented on .github/workflows/ci.yml
> +        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.out ./...
Add empty line

2023-04-20 15:41 UTC, rodneyosodo commented on .gitignore
> +go.work
Add empty line

2023-04-21 11:57 UTC, rodneyosodo requested changes

2023-04-21 11:57 UTC, rodneyosodo commented on .github/workflows/ci.yml
> +        run: go test -mod=vendor -v --race -covermode=atomic -coverprofile cover.out ./...
Add empty line

2023-04-24 15:04 UTC, rodneyosodo approved these changes

2023-04-27 11:03 UTC, dborovcanin approved these changes

2023-04-27 11:48 UTC, drasko approved these changes
LGTM

2023-04-27 12:47 UTC, merged